### ISSUE TITLE
Reporting wrong version

### ISSUE THREAD

**Issue by obi12341** [Ysurac/openmptcprouter#2499]
SSH Login Banner is always reporting wrong version:
```
BusyBox v1.33.2 (2022-05-17 22:11:28 UTC) built-in shell (ash)

   ___                 __  __ ___ _____ ___ ___              _
  / _ \ _ __  ___ _ _ |  \/  | _ \_   _/ __| _ \_ _ ___ _  _| |_ ___ _ _
 | (_) | '_ \/ -_) ' \| |\/| |  _/ | || (__|  _/ '_/ _ \ || |  _/ -_) '_|
  \___/| .__/\___|_||_|_|  |_|_|   |_| \___|_| |_| \___/\_,_|\__\___|_|
       |_|
------------------------------------------------------------------------------
   (r0+16594-ce92de8c8c)
------------------------------------------------------------------------------
-----------------------------------------------------
 PACKAGE:     openmptcprouter
 VERSION:     v0.58.5
 TARGET:      x86_64
 ARCH:        x86_64

 BUILD REPO:  https://github.com/ysurac/openmptcprouter
 BUILD DATE:  Mon Aug 22 21:41:55 UTC 2022
-----------------------------------------------------
```

although I have upgraded from 0.58.5 to 0.59.0. Backend is reporting the right version (see screenshot) but also always finds newer version to upgrade to.

<img width="434" alt="Bildschirmfoto 2022-08-29 um 23 30 57" src="https://user-images.githubusercontent.com/199624/187302906-917a6fe5-f96a-4f9a-a4f5-0b7ba0bd9fb7.png">

**Comment by Ysurac** [comment]
Release if fixed in 0.59.1 for the SSH login banner.
For sysupgrade this will be in a next minor release.

**Comment by hairy-dog** [comment]
I am offered upgrade to 0.59.1 but after running the sysupgrade and the automatic reboot, I am still on 0.59-5.4

**Comment by hairy-dog** [comment]
![59 1](https://user-images.githubusercontent.com/10561885/187560000-59c4f939-cdbd-4509-9c99-fbd01361a398.jpg)
It looks as if the sysupgrade is fetching the old file.

**Comment by Ysurac** [comment]
It's fixed now. CDN cache not flushed for this part, so this was still old release.

**Comment by fsufyan** [comment]
I am still getting this on RPI 3B+
![Screenshot 2022-08-31 at 09 42 20](https://user-images.githubusercontent.com/36089616/187621680-1583e102-f8b8-436c-8cae-0f158c9a7ef5.png)

**Comment by gregorst3** [comment]
> It's fixed now. CDN cache not flushed for this part, so this was still old release.

I upgraded to 0.59.1 but sysupgrade still shows to update to 0.59.1
<img width="1950" alt="image" src="https://user-images.githubusercontent.com/12485463/188311425-ec857384-ef22-4e50-9769-ccf5201a5f85.png">

**Comment by Ysurac** [comment]
I don't see this as a big problem, but this will be solved in next release.

**Comment by gregorst3** [comment]
> I don't see this as a big problem, but this will be solved in next release.

Absolutely not a problem at all, was just to report!
Thanks fo this awesome project

**Comment by ogmkp** [comment]
Juste a message to don't forget this ;)
