### ISSUE TITLE
Last snapshot kernel 5.4 x86_64 compiled with problems.

### ISSUE THREAD

**Issue by vempire-ghost** [Ysurac/openmptcprouter#3406]
The image the has only 9MB and don't initiate.

**Comment by Ysurac** [comment]
Should be fixed when current snapshot compilation will finish... I hope... No problem when compiled manually.

**Comment by vempire-ghost** [comment]
The problem is still present in the last snapshot compiled today. And the x86_64 is the only affected.

**Comment by Ysurac** [comment]
It's working correctly now.
