### ISSUE TITLE
OMR-Bypass Not working

### ISSUE THREAD

**Issue by MarcelHService** [Ysurac/openmptcprouter#3770]
## Expected Behavior
OMR-Bypass as Domain 
Domain: 'https://promods.net' Interface eth0.10 

## Current Behavior
OMR-Bypass Not working. Same isp on the mobile phone it work the Domain. In Ethernet its Not Working. 
Ip got blocked by Promods.net
I have try to Chance the Interface but Same result. The Networksettings on the PC are:
IPv4: 192.168.100.255
Gateway: 192.168.100.1
DNS: 192.168.100.1

## Specifications

  - OpenMPTCProuter version: openmptcprouter v0.61-6.6 r0+27346
  - OpenMPTCProuter VPS version: 6.6.36-x64v3-xanmod1 0.1031
  - OpenMPTCProuter VPS provider: Ionos Germany
  - OpenMPTCProuter platform: x64

**Comment by Ysurac** [comment]
Can you try latest snapshot kernel 6.6 ? https://github.com/Ysurac/openmptcprouter/wiki/Snapshots
I fixed some issues in omr-bypass

**Comment by MarcelHService** [comment]
Still the Same Problem.

on https://promods.net/

> Request Blocked
Your request to access promods.net has been blocked because your IP address appears to be abusive

> 

Versions

Server: 6.6.36-x64v3-xanmod1 0.1032-test
Router: openmptcprouter v0.62-snapshot-6.6 r0+28308-c06d4df974
Default Proxy: XRay VMESS
Default VPN: A Dead Simple VPN

Server Log

> Jan 17 20:32:14 OpenMPTCProuter daemon.err dnsmasq[1]: nftset inet fw4 omr_dscp_cs2_6 Error: Could not resolve hostname: Name has no usable address

>

**Comment by Ysurac** [comment]
I would need, via SSH on the router, the result of ```nft list ruleset```

**Comment by MarcelHService** [comment]
Here there are.

https://pastebin.com/1S3i4aSu

**Comment by Ysurac** [comment]
I find ips for promods.net, but not in good section. I would also need the result of ```uci show omr-bypass```

**Comment by MarcelHService** [comment]
sure here there are https://pastebin.com/PgcQiQMZ

**Comment by Ysurac** [comment]
The domain must be without https://, so only promods.net

**Comment by MarcelHService** [comment]
i have test it but same result.

when i do as domain www.whatismyip.com or whatismyip.com then i get still the VPS Server IP not the WAN Ip

**Comment by MarcelHService** [comment]
i don't know what i do but now its work.

Thanks a lot for your Support :)

**Comment by ioogithub** [comment]
Hi [MarcelHService](https://github.com/MarcelHService), I see you were able to get OMR-bypass working on v0.61-6.6 r0+27346 I am on a similar version it is appears to work on 6.1. Were you able to get omr-bypass working with any of the latest shapshots or any other newer versions? If so could you please advise on which version you got working? I have OMR-bypass working as expected in version 0.61rc2-6.6 however no version past 6.1 are working. I have tested all of the fresh images between 0.61 up to the latest 0.64-snapshot-6.12 r0+31388-17badf6099 without success.

OMr-bypass will temporarily work on all of these versions for a short time only after the Save & Apply button is clicked on the wizard page but after a reboot or after some time a script runs and breaks it again. Are you aware of which scripts are likely involved in setting these routes? I am willing to look into the issue more deeply but I don't really know where to start.

**Comment by MarcelHService** [comment]
Hi,
I have Version v0.63-6.6 on the Router and Version 6.12.41-x64v3-xanmod1 0.1039 on the VPS installed and it works fine for me.
