### ISSUE TITLE
Can openmptcprouter be successfully used if VPS only has IPv6?

### ISSUE THREAD

**Issue by RabbitJun** [Ysurac/openmptcprouter#3908]
As is well known, openmptcprouter works well with IPv4 VPS. So if VPS only has IPv6, can Openmptcprouter be successfully used? How to configure openmptcprouter? What are the changes from the usual configuration method? Thank you for your response

**Comment by RabbitJun** [comment]
Thank you, I will try. IPv6 will become increasingly popular, I believe.

**Comment by RabbitJun** [comment]
![Image](https://github.com/user-attachments/assets/3eaae165-1c8a-41a7-8b9a-4e7cfb9e5ad9)
![Image](https://github.com/user-attachments/assets/381f43d2-47fd-4a76-8a63-0f2f29412633)
![Image](https://github.com/user-attachments/assets/8ae907f3-aa42-4777-8233-4d9f10d88046)

Did I do something wrong? The Wan6 router can ping the VPS, but the displayed IP is not the VPS IP

**Comment by Ysurac** [comment]
You can ping IPv6 server's IP via SSH on the router ?
You need also to disable 6in4 in System->OpenMPTCProuter, "Advanced settings" tab.

**Comment by RabbitJun** [comment]
Yes, I have tried all these options but still couldn't get the VPS IP. This must mean that I didn't succeed.

![Image](https://github.com/user-attachments/assets/cbb12a01-6eec-4748-9ba7-92b54e69b8c0)

**Comment by Ysurac** [comment]
What is the result of ```ip -6 r``` ?

**Comment by RabbitJun** [comment]
root@Router:~# ip -6 r
2409:8d20:f04:1e4f::30e dev eth4 metric 615 pref medium
unreachable 2409:8d20:f04:1e4f::/64 dev lo proto static metric 2147483647 pref medium
240e:3ae:965:d2c0:20c:29ff:feaa:ed86 via 2409:8d20:f04:1e4f:: dev eth4 metric 1 pref medium
240e:3ae:965:d2c0:20c:29ff:feaa:ed86 via 2409:8d20:f04:1e4f:: dev eth4 metric 15 pref medium
240e:3ae:965:d2c0:20c:29ff:feaa:ed86 via fe80::4245:daff:fee5:2122 dev eth0 metric 19 pref medium
240e:479:800:73d:: dev eth0 metric 69 pref medium
240e:479:800:73d:82af:caff:fe88:133 via 2409:8d20:f04:1e4f:: dev eth4 metric 1 pref medium
240e:479:800:73d:82af:caff:fe88:133 via 2409:8d20:f04:1e4f:: dev eth4 metric 15 pref medium
240e:479:800:73d:82af:caff:fe88:133 via fe80::4245:daff:fee5:2122 dev eth0 metric 19 pref medium
240e:479:800:73d::/64 dev eth0 metric 69 pref medium
240e:479:800:73d::/64 dev eth0 metric 618 pref medium
240e:479:800:73d::/64 dev eth0 metric 619 pref medium
unreachable 240e:479:800:73d::/64 dev lo proto static metric 2147483647 pref medium
fd32:a7e0:1162::/64 dev eth4 metric 615 pref medium
unreachable fd32:a7e0:1162::/64 dev lo proto static metric 2147483647 pref medium
unreachable fd83:e3da:7e57::/48 dev lo proto static metric 2147483647 pref medium
fe80::4245:daff:fee5:2122 dev eth0 metric 618 pref medium
fe80::4245:daff:fee5:2122 dev eth0 metric 619 pref medium
fe80::a617:a55b:f6ce:190a dev eth4 metric 615 pref medium
fe80::/64 dev br-lan proto kernel metric 256 pref medium
fe80::/64 dev eth1 proto kernel metric 256 pref medium
fe80::/64 dev eth3 proto kernel metric 256 pref medium
fe80::/64 dev eth4 proto kernel metric 256 pref medium
fe80::/64 dev phy0-ap0 proto kernel metric 256 pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
default via 240e:479:800:73d:: dev eth0 metric 69 pref medium
default via fe80::a617:a55b:f6ce:190a dev eth4 metric 615 pref medium
default via fe80::4245:daff:fee5:2122 dev eth0 metric 618 pref medium
default via fe80::4245:daff:fee5:2122 dev eth0 metric 619 pref medium
default via 2409:8d20:f04:1e4f:: dev eth4 metric 1024 pref medium

**Comment by Ysurac** [comment]
```curl -k -6 https://[<vpsip>]:65500/``` ?

**Comment by RabbitJun** [comment]
curl: (7) Failed to connect to...

Okay, I know what the problem is now.

I checked the port on VPS. 65500 is not running on tcp6

![Image](https://github.com/user-attachments/assets/1084599d-d56c-41f6-8331-3bd0466a3a24)

**Comment by Ysurac** [comment]
True, it should. Seems that I have an error in my script.

**Comment by Ysurac** [comment]
Should be fixed in snapshot script: ```wget -O - https://www.openmptcprouter.com/server-test/debian-x86_64.sh | KERNEL="6.12" sh```

**Comment by RabbitJun** [comment]
root@Router:~# curl -k -6 https://[ipv6]:65500
"Welcome to OpenMPTCProuter Server part 

But the router still can't get the VPS IP, but I have a feeling that it's about to succeed

![Image](https://github.com/user-attachments/assets/79e76f2b-cd5d-4485-a46c-83bd00cf56e7)

**Comment by Ysurac** [comment]
Stay on shadowsocks-rust with OpenVPN as VPN, easier to debug.
Can you give me, via SSH on the router, the result of ```ip -6 r``` and ```logread``` ?
And on the VPS, the result of ```curl ip.openmptcprouter.com``` ?

**Comment by RabbitJun** [comment]
I used the command to get txt, and the content is all in the attachment

{
  echo "===== [1] IPv6 路由表 (ip -6 route) ====="
  ip -6 route
  echo -e "\n===== [2] 系统日志 (logread) ====="
  logread
  echo -e "\n===== [3] 公网IP检测 (curl) ====="
  curl -s ip.openmptcprouter.com
  echo -e "\n===== [4] Shadowsocks 服务日志 (journalctl) ====="
  journalctl -u shadowsocks-go --no-pager -n 20
} > debug_results.txt 2>&1

[debug_results_router.txt](https://github.com/user-attachments/files/19707874/debug_results_router.txt)
[debug_results_vps.txt](https://github.com/user-attachments/files/19707875/debug_results_vps.txt)
